# Generated by Django 5.0.7 on 2024-08-29 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthprediction',
            old_name='medication_needs',
            new_name='under_medication',
        ),
    ]
